CREATE TABLE  "DEMO_PROJ_STATUS" 
   (	"CD" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_STATUS_PK" PRIMARY KEY ("CD")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_TEAM_MEMBERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255), 
	"PROFILE" VARCHAR2(4000), 
	"PHOTO_FILENAME" VARCHAR2(100), 
	"PHOTO_BLOB" BLOB, 
	"PHOTO_MIMETYPE" VARCHAR2(255), 
	"PHOTO_CHARSET" VARCHAR2(128), 
	"PHOTO_LAST_UPDATED" DATE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TEAM_MEMBERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TEAM_MEMBERS_UK" UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJECTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_LEAD" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"STATUS_CD" VARCHAR2(15) NOT NULL ENABLE, 
	"COMPLETED_DATE" DATE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DEMO_PROJECTS_UK" UNIQUE ("NAME")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_MILESTONES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"DUE_DATE" DATE NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_MILESTONES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_TASKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"MILESTONE_ID" NUMBER, 
	"ASSIGNEE" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TASKS_UK" UNIQUE ("PROJECT_ID", "NAME")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_TASK_TODOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_ID" NUMBER NOT NULL ENABLE, 
	"ASSIGNEE" NUMBER, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"IS_COMPLETE_YN" VARCHAR2(1), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TASK_TODOS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_COMMENTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_TEXT" VARCHAR2(4000) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_TASK_LINKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_ID" NUMBER NOT NULL ENABLE, 
	"LINK_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"URL" VARCHAR2(255), 
	"APPLICATION_ID" NUMBER, 
	"APPLICATION_PAGE" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TASK_LINKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DEMO_PROJ_TASK_LINK_LTY_CH" CHECK ( link_type in ('URL','Application')) ENABLE
   )
/
CREATE TABLE  "DEMO_PROJ_CONSTRAINTS" 
   (	"CONSTRAINT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "DEMO_PROJ_CONST_LOOKUP_PK" PRIMARY KEY ("CONSTRAINT_NAME")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "DEMO_PROJ_COMMENTS" ADD CONSTRAINT "DEMO_PROJ_COMMENT_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "DEMO_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJ_MILESTONES" ADD CONSTRAINT "DEMO_PROJ_MSTONE_PROJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "DEMO_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJECTS" ADD CONSTRAINT "DEMO_PROJ_STATUS_FK" FOREIGN KEY ("STATUS_CD")
	  REFERENCES  "DEMO_PROJ_STATUS" ("CD") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASK_LINKS" ADD CONSTRAINT "DEMO_PROJ_TASK_LINK_PRJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "DEMO_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASK_LINKS" ADD CONSTRAINT "DEMO_PROJ_TASK_LINK_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES  "DEMO_PROJ_TASKS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASKS" ADD CONSTRAINT "DEMO_PROJ_TASK_MSTONE_FK" FOREIGN KEY ("MILESTONE_ID")
	  REFERENCES  "DEMO_PROJ_MILESTONES" ("ID") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASKS" ADD CONSTRAINT "DEMO_PROJ_TASK_PROJECT_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "DEMO_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASKS" ADD CONSTRAINT "DEMO_PROJ_TASK_TEAM_MEM_FK" FOREIGN KEY ("ASSIGNEE")
	  REFERENCES  "DEMO_PROJ_TEAM_MEMBERS" ("ID") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASK_TODOS" ADD CONSTRAINT "DEMO_PROJ_TASK_TODO_PRJ_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "DEMO_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASK_TODOS" ADD CONSTRAINT "DEMO_PROJ_TASK_TODO_TM_FK" FOREIGN KEY ("ASSIGNEE")
	  REFERENCES  "DEMO_PROJ_TEAM_MEMBERS" ("ID") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "DEMO_PROJ_TASK_TODOS" ADD CONSTRAINT "DEMO_PROJ_TASK_TODO_TSK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES  "DEMO_PROJ_TASKS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "DEMO_PROJECTS" ADD CONSTRAINT "DEMO_PROJ_TEAM_MEMBER_FK" FOREIGN KEY ("PROJECT_LEAD")
	  REFERENCES  "DEMO_PROJ_TEAM_MEMBERS" ("ID") ON DELETE SET NULL ENABLE
/
